name: Eleventy Build
#on: [push]

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.3
        with:
          install_dependencies: true
          args: --output dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
